version: '3.1'

services:

  data-lake:
    image: mongo:latest
    deploy:
      mode: global
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: 'data-lake'
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    networks:
      data-lake-network:
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  data-lake-network:
